// principales
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

// Esta logeado
export const IS_LOGGED = "IS_LOGGED";

// Error en el logeo
export const LOGIN_HAS_ERROR = "LOGIN_HAS_ERROR";

// Se esta realizado un envio (dispatch) para el logeo (dispatch)
export const LOGIN_IS_LOADING = "LOGIN_IS_LOADING";

//REGISTRO

export const REGISTER = "REGISTER";

// Error en el register
export const REGISTER_HAS_ERROR = "REGISTER_HAS_ERROR";

// Se esta realizado un envio para un registro (dispatch)
export const REGISTER_IS_LOADING = "REGISTER_IS_LOADING";

export const MAPA = "MAPA";

export const ACTUALIZAR_COORDENADAS = "ACTUALIZAR_COORDENADAS"

export const ACTUALIZAR_COORDENADAS_REGISTRO = "ACTUALIZAR_COORDENADAS_REGISTRO"

export const MAPA_REGISTRO_VENDEDOR = "MAPA_REGISTRO_VENDEDOR";

export const MAPA_MODIFICAR_COMERCIO = "MAPA_MODIFICAR_COMERCIO";

export const MAPA_PAGINA_COMERCIO = "MAPA_PAGINA_COMERCIO";

export const RENDERIZAR_MAPA = "RENDERIZAR_MAPA";

export const RENDERIZAR_MAPA_MODIFICAR_COMERCIO = "RENDERIZAR_MAPA_MODIFICAR_COMERCIO;"

export const FILA_CLICKADA = "FILA_CLICKADA";

export const FILA_CLICKADA2 = "FILA_CLICKADA2";

export const FILA_CLICKADA3 = "FILA_CLICKADA3";

export const FILA_CLICKADA4 = "FILA_CLICKADA4";

export const FILA_CLICKADA5 = "FILA_CLICKADA5";

//MAIN ADMIN

export const CATALOGO_PRODUCTOS_ADMIN = "CATALOGO_PRODUCTOS_ADMIN";

export const GESTION_COMERCIOS = "GESTION_COMERCIOS";

export const GESTION_DENUNCIAS = "GESTION_DENUNCIAS";

export const GESTION_USUARIOS_REGISTRADOS = "GESTION_USUARIOS_REGISTRADOS";

export const GESTION_CATALOGO_PRODUCTOS = "GESTION_CATALOGO_PRODUCTOS";

export const GESTION_PAG_COMERCIO = "GESTION_PAG_COMERCIO";

export const GESTION_FEEDBACKS = "GESTION_FEEDBACKS";

export const GESTION_PERFILES_USUARIO = "GESTION_PERFILES_USUARIO";

//MAIN

export const MODIFICARPERFILREGISTRADO = "MODIFICAR_PERFIL_REGISTRADO";

export const MODIFICARPERFILREGISTRADO_HAS_ERROR =
  "MODIFICAR_PERFIL_REGISTRADO_HAS_ERROR";

export const MODIFICARPERFILREGISTRADO_IS_LOADING =
  "MODIFICAR_PERFIL_REGISTRADO_IS_LOADING";

export const MODIFICARPERFILVENDEDOR = "MODIFICAR_PERFIL_VENDEDOR";

export const MODIFICARPERFILVENDEDOR_HAS_ERROR =
  "MODIFICAR_PERFIL_VENDEDOR_HAS_ERROR";

export const MODIFICARPERFILVENDEDOR_IS_LOADING =
  "MODIFICAR_PERFIL_VENDEDOR_IS_LOADING";

export const CAMBIAR_PASS_REGISTRADO = "CAMBIAR_PASS_REGISTRADO";

export const CAMBIAR_PASS_REGISTRADO_IS_LOADING =
  "CAMBIAR_PASS_REGISTRADO_IS_LOADING";

export const CAMBIAR_PASS_REGISTRADO_HAS_ERROR =
  "CAMBIAR_PASS_REGISTRADO_HAS_ERROR";

export const CAMBIAR_PASS_VENDEDOR = "CAMBIAR_PASS_VENDEDOR";

export const CAMBIAR_PASS_VENDEDOR_IS_LOADING =
  "CAMBIAR_PASS_VENDEDOR_IS_LOADING";

export const CAMBIAR_PASS_VENDEDOR_HAS_ERROR =
  "CAMBIAR_PASS_VENDEDOR_HAS_ERROR";

export const PERFILREGISTRADO = "PERFILREGISTRADO";

export const PERFILREGISTRADO_IS_LOADING = "PERFILREGISTRADO_IS_LOADING";

export const PERFILREGISTRADO_HAS_ERROR = "PERFILREGISTRADO_HAS_ERROR";

export const PERFILVENDEDOR = "PERFILVENDEDOR";

export const COMERCIOS = "COMERCIOS";

export const COMERCIOS_HAS_ERROR = "COMERCIOS_HAS_ERROR";

export const COMERCIOS_IS_LOADING = "COMERCIOS_IS_LOADING";

export const COMERCIOS_DETALLE = "COMERCIOS_DETALLE";

//MAINVENDEDOR

export const CATALOGO_VENDEDOR = "CATALOGO_VENDEDOR";

export const CATALOGO_VENDEDOR_HAS_ERROR = "CATALOGO_VENDEDOR_HAS_ERROR";

export const CATALOGO_VENDEDOR_IS_LOADING = "CATALOGO_VENDEDOR_IS_LOADING";

export const CATALOGO = "CATALOGO";

export const CATALOGO_HAS_ERROR = "CATALOGO_HAS_ERROR";

export const CATALOGO_IS_LOADING = "CATALOGO_IS_LOADING";

export const CATALOGO_DETALLE = "CATALOGO_DETALLE";

export const MODIFICARCOMERCIO = "MODIFICARCOMERCIO";

export const MODIFICARCOMERCIO_HAS_ERROR = "MODIFICARCOMERCIO_HAS_ERROR";

export const MODIFICARCOMERCIO_IS_LOADING = "MODIFICARCOMERCIO_IS_LOADING";

//CATALOGO

export const CAMPO_ERROR = "CAMPO_ERROR";

export const NO_ERROR = "NO_ERROR";

export const INSERTAR = "INSERTAR";

export const INSERTAR_HAS_ERROR = "INSERTAR_HAS_ERROR";

export const INSERTAR_IS_LOADING = "INSERTAR_IS_LOADING";

export const ELIMINAR = "ELIMINAR";

export const ELIMINAR_HAS_ERROR = "ELIMINAR_HAS_ERROR";

export const ELIMINAR_IS_LOADING = "ELIMINAR_IS_LOADING";

export const MODIFICAR = "MODIFICAR";

export const MODIFICAR_HAS_ERROR = "MODIFICAR_HAS_ERROR";

export const MODIFICAR_IS_LOADING = "MODIFICAR_IS_LOADING";

export const MAINADMIN = "MAINADMIN";

export const MAINADMIN_HAS_ERROR = "MAINADMIN_HAS_ERROR";

export const MAINADMIN_IS_LOADING = "MAINADMIN_IS_LOADING";

export const MAINVENDEDOR = "MAINVENDEDOR";

export const MAINVENDEDOR_HAS_ERROR = "MAINVENDEDOR_HAS_ERROR";

export const MAINVENDEDOR_IS_LOADING = "MAINVENDEDOR_IS_LOADING";

export const MAIN = "MAIN";

export const MAIN_HAS_ERROR = "MAIN_HAS_ERROR";

export const MAIN_IS_LOADING = "MAIN_IS_LOADING";

//CATALOGO_CLIENTE

export const CATALOGO_CLIENTES = "CATALOGO_CLIENTES";

export const CATALOGO_CLIENTES_IS_LOADING = "CATALOGO_CLIENTES_IS_LOADING";

export const CATALOGO_CLIENTES_HAS_ERROR = "CATALOGO_CLIENTES_HAS_ERROR";

export const CATEGORIA = "CATEGORIA";

export const CATEGORIA_VENDEDOR = "CATEGORIA_VENDEDOR";

export const NO_CATEGORIA = "NO_CATEGORIA";

//CATALOGO_CLIENTE_FAST

export const CATALOGO_CLIENTES_FAST = "CATALOGO_CLIENTES_FAST";

export const CATALOGO_CLIENTES_FAST_IS_LOADING =
  "CATALOGO_CLIENTES_FAST_IS_LOADING";

export const CATALOGO_CLIENTES_FAST_HAS_ERROR =
  "CATALOGO_CLIENTES_FAST_HAS_ERROR";

//PAGINA COMERCIO

export const PAG_COMERCIO = "PAG_COMERCIO";

export const PAG_COMERCIO_MAPA = "PAG_COMERCIO_MAPA";

//PAGINA PRODUCTO

export const PAG_PRODUCTO = "PAG_PRODUCTO";

//PAGINA PRODUCTO VENDEDOR

export const PAG_PRODUCTO_VENDEDOR = "PAG_PRODUCTO_VENDEDOR";

//FEEDBACK

export const FEEDBACK = "FEEDBACK";

export const FEEDBACK_HAS_ERROR = "FEEDBACK_HAS_ERROR";

export const FEEDBACK_IS_LOADING = "FEEDBACK_IS_LOADING";

//DENUNCIA

export const DENUNCIA = "DENUNCIA";

export const DENUNCIA_HAS_ERROR = "DENUNCIA_HAS_ERROR";

export const DENUNCIA_IS_LOADING = "DENUNCIA_IS_LOADING";

//VER_FEEDBACKS_COMERCIO

export const VER_FEEDBACKS_COMERCIO = "VER_FEEDBACKS_COMERCIO";

export const VER_FEEDBACKS_COMERCIO_HAS_ERROR =
  "VER_FEEDBACKS_COMERCIO_HAS_ERROR";

export const VER_FEEDBACKS_COMERCIO_IS_LOADING =
  "VER_FEEDBACKS_COMERCIO_IS_LOADING";

export const VER_FEEDBACKS_COMERCIO_PRODUCTOS = "VER_FEEDBACKS_COMERCIO_PRODUCTOS";

export const VER_FEEDBACKS_PRODUCTOS = "VER_FEEDBACKS_PRODUCTOS";

export const VER_FEEDBACKS_PRODUCTO = "VER_FEEDBACKS_PRODUCTO";

//BUSCADOR
export const BUSCADOR = "BUSCADOR";

export const BUSCADOR_IS_LOADING = "BUSCADOR_IS_LOADING";

export const BUSCADOR_HAS_ERROR = "BUSCADOR_HAS_ERROR";

export const BUSCADOR_MOSTRAR = "BUSCADOR_MOSTRAR";

export const BUSCADOR_NO_MOSTRAR = "BUSCADOR_NO_MOSTRAR";

export const TERMINAR_LOADER = "TERMINAR_LOADER";
